name: Trash-Bot-kun

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools poetry
        poetry install

    - name: Run bot
      env:
        SECRET_MONDAY: ${(  secrets.SECRET_MONDAY )}
        SECRET_TUESDAY: ${( secrets.SECRET_TUESDAY )}
        SECRET_WEDNESDAY: ${( secrets.SECRET_WEDNESDAY )}
        SECRET_THURSDAY: ${( secrets.SECRET_THURSDAY )}
        SECRET_FRIDAY: ${( secrets.SECRET_FRIDAY )}
      run: |
        python main.py \
          --monday ${SECRET_MONDAY} \
          --tuesday ${SECRET_TUESDAY} \
          --wednesday ${SECRET_WEDNESDAY} \
          --thursday ${SECRET_THURSDAY} \
          --friday ${SECRET_FRIDAY}  